### ISSUE TITLE
force_code_sign_identity applied to linked librarires

### ISSUE THREAD

**Issue by gaultierq** [bitrise-io/steps-xcode-archive#105]
Using the following parameters :
- force_team_id
- force_code_sign_identity
- force_provisioning_profile_specifier
- force_provisioning_profile

the build fails because these parameters are used as well for the linked librairies, which are usually automatically signed.

**Comment by doomsayer13** [comment]
Hi @gaultierq ,
Thanks for reporting an issue, we'll check it ASAP.

**Comment by godrei** [comment]
Hi @gaultierq ,
by using the mentioned inputs the step adds:

- DEVELOPMENT_TEAM
- CODE_SIGN_IDENTITY
- PROVISIONING_PROFILE_SPECIFIER
- PROVISIONING_PROFILE

envs with the defined value to the `xcodebuild` command call and xcodebuild behaves this way, it forces the defined settings also for linked libraries.

In your case you can not use the forceX properties.

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!
