### ISSUE TITLE
Xcode Archive failed : could not build Objective-C module 'PSPDFKit'

### ISSUE THREAD

**Issue by Jur4s** [bitrise-io/steps-xcode-archive#107]
Hello,

I have an issue with a working project when trying to build the project:

The project is a library project, with a application target in it.
So the application target implement the library code.

My library use PSPDFkit cocoapod dependency and it's seems to failed when trying to build my application project.

My podfile
```
target 'LibTarget' do
  use_frameworks!

  pod 'PSPDFKit', podspec:'XXXX'
  pod 'Zip'

end

target 'AppTarget' do
  use_frameworks!
  pod 'EasyPeasy'
end

```

The zip and EasyPeasy pod is installed and compiled during the Cocoapod Step, but I don't see any log about the PSPDFkit.

Then during the Xcode step I have the following error : 
```
❌  /Users/vagrant/git/Pods/PSPDFKit/PSPDFKit.framework/Headers/PSPDFKit.h:26:9: 'PSPDFKit/PSPDFRotation.h' file not found
#import <PSPDFKit/PSPDFRotation.h>
        ^
❌  /Users/vagrant/git/PDFViewer/Managers/Prepare/PreparePdfDataManager.swift:10:8: could not build Objective-C module 'PSPDFKit'
import PSPDFKit
```

In local, everything works perfectly.

Thanks for your help,
Kinds regards,

Jonas Freres

**Comment by viktorbenei** [comment]
Hi @Jur4s ,

Did you contact our support with this question? I remember seeing this there, or something really similar..

**Comment by viktorbenei** [comment]
If you'd still need help with this issue please share the related build's bitrise.io URL so that we can check its logs & configs! :)

**Comment by viktorbenei** [comment]
Got it, thanks for reporting @Jur4s ! :)
