### ISSUE TITLE
iOS Archive failed with exit status code 65

### ISSUE THREAD

**Issue by jhanzo** [bitrise-io/steps-xcode-archive#114]
Hi !

I sent you 2 emails 2 days ago about a very annoying issue. Indeed, we don't succeed in solving this issue.

```
** ARCHIVE FAILED **
You can find the last couple of lines of Xcode's build log above, but the full log is also available in the raw-xcodebuild-output.log
The log file is stored in $BITRISE_DEPLOY_DIR, and its full path is available in the $BITRISE_XCODE_RAW_RESULT_TEXT_PATH environment variable
(value: /Users/vagrant/deploy/raw-xcodebuild-output.log)
Archive failed, error: exit status 65
```
 
By reading my archive logs, something went wrong while validating project but I don't know why and how to find the cause. This is the first time we have a such issue and Google results have not helped me yet.

**Comment by BirmacherAkos** [comment]
Hi!

Could you please send the build log of the failing build?

**Comment by jhanzo** [comment]
by email ?

**Comment by BirmacherAkos** [comment]
You can send your build log via the on-site chat on Bitrise (bottom right corner).

![screen shot 2018-06-21 at 17 51 27](https://user-images.githubusercontent.com/37296013/41730305-ca5d4328-757b-11e8-84c8-3da26f36d5a1.png)

**Comment by jhanzo** [comment]
Ok right ! Done !

**Comment by jhanzo** [comment]
Ok found ! The error was about a missing framework in "Embed Frameworks"...

So painfull to debug this kind of error ...

**Comment by viktorbenei** [comment]
In a case like this you should check the raw xcodebuild log, which is attached to the build by default. That's the full, unfiltered Xcode build log, which includes all the details, but is usually super verbose that's why it's attached as a file to the build: https://discuss.bitrise.io/t/xcode-exit-code-65-exit-code-66-raw-xcodebuild-output-log/813/2?u=viktorbenei

**Comment by trancelife** [comment]
the same issue. Please, help me
[raw-xcodebuild-output.log](https://github.com/bitrise-io/steps-xcode-archive/files/2374853/raw-xcodebuild-output.log)

**Comment by bitce** [comment]
Hi @trancelife!

Based on the log it seems that you have specified a 'Distribution' export type but your profile is signed for Development. Is that correct?

To provide assistance, please send us a log file or a URL to the build as well, preferably on our on site chat :)

**Comment by bitce** [comment]
Hi @trancelife!

Based on the log it seems that you have specified a 'Distribution' export type but your profile is signed for Development. Is that correct?

To provide assistance, please send us a log file or a URL to the build as well, preferably on our on site chat :)
