### ISSUE TITLE
IPA export fails in step version 2.4.11+

### ISSUE THREAD

**Issue by fadookie** [bitrise-io/steps-xcode-archive#120]
Hello,
After updating to xcode-archive version 2.4.11 and then 2.4.12, I am getting a failure on one of my closed-source builds. I'm hesitant to include the full log on a public issue tracker in case it contains any sensitive information, but the failure is here in the following log excerpt:

```
Exporting ipa from the archive...

Exporting ipa with ExportOptions.plist
No custom export options content provided, generating export options...
auto-detect export method specified
using the archive profile's (Thrive Distribution) export method: app-store
Failed to get target (React) bundle id: key: string("INFOPLIST_FILE") not found in: serialized.Object(serialized.Object{"GCC_WARN_ABOUT_MISSING_PROTOTYPES":"YES", "VERSION_INFO_FILE":"React_vers.c", "CODESIGNING_FOLDER_PATH":"/Users/vagrant/Library/Developer/Xcode/DerivedData/React-ffwqlnokchpmutajnemgqrgnryey/Build/Products/Release-iphoneos/libReact.a",
```

Downgrading to xcode-archive 2.4.10 fixes the issue.

We are on the latest [osx-vs4mac-stable stack](https://github.com/bitrise-io/bitrise.io/blob/d119e8a2676eb01caaf5eb0242016d9cf8039924/system_reports/osx-vs4mac-stable.log).

**Comment by bkobilansky** [comment]
We are also seeing a similar issue. I have not yet downgraded to see if it resolves it, but our logs state:

```
Exporting ipa from the archive...

Exporting ipa with ExportOptions.plist
No custom export options content provided, generating export options...
export-method specified: enterprise
no scheme found with name: <our_scheme_name> in workspace: <our_workspace_name>
```

**Comment by fphilipe** [comment]
Our builds started failing with the update from 2.4.10 to 2.4.12.

The `xcpretty` output was showing this (haven't tried without `xcpretty`):

```
Failed to find Codesign Groups
generated export options content:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>method</key>
		<string>enterprise</string>
	</dict>
</plist> <nil>
```

Reverting to 2.4.10 I see this instead:

```
Profile name filter - removes profile with name: BitriseBot-Wildcard
generated export options content:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>method</key>
		<string>enterprise</string>
		<key>provisioningProfiles</key>
		<dict>
			<key>REDACTED</key>
			<string>REDACTED</string>
		</dict>
		<key>signingCertificate</key>
		<string>iPhone Distribution: REDACTED</string>
		<key>teamID</key>
		<string>REDACTED</string>
	</dict>
</plist> <nil>
```

**Comment by gaultierq** [comment]
same here `no scheme found with name: xxx in workspace: ios/xxx.xcworkspace`
downgrading

**Comment by BirmacherAkos** [comment]
Hi all!

Thanks for the reports, the Tooling Team is checking the issue.
Sorry for the inconvenience.

**Comment by blbradley** [comment]
Can confirm behavior and that rollback to 2.4.10 is the current resolution.

**Comment by godrei** [comment]
Hi, thanks for the reports!

Could you please write us on the on-site-chat and send us:

- if you use workspace: your .xcworkspace and the embedded .xcodeproj files
- if you use project: your .xcodeproj file
- also make sure to include the Build’s URL

i would need to have a look them to identify the issue.

**Comment by KoCMoHaBTa** [comment]
Thanks @godrei for the info - i've sent my details, using the site chat, but no response yet. Hopefully the team will manage to find the solution.

**Comment by godrei** [comment]
Hi all,
thanks for the issue reports and projects you provided us for testing.
We released a new version of the step: https://github.com/bitrise-io/steps-xcode-archive/releases/tag/2.4.13
