### ISSUE TITLE
iCloudContainerEnvironment doesn't make it into the generated exportOptionsPlist

### ISSUE THREAD

**Issue by vanwagonet** [bitrise-io/steps-xcode-archive#125]
Even when explicitly specified in the step configuration, the exportOptionsPlist is missing the iCloudContainerEnvironment.

```
error: exportArchive: exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was provided
```

**Comment by bootstraponline** [comment]
:wave: this is a blocking issue for us

I thought the problem was solved in https://github.com/bitrise-io/steps-xcode-archive/issues/111

**Comment by viktorbenei** [comment]
Hi @vanwagonet , can you please copy paste the related build's bitrise.io URL, so that we can look into its logs & config?

**Comment by bitce** [comment]
You might want to run your builds on the 2.4.10 step version, as other users have experienced that to still be working, but please do as Viktor requested so we can look into it! 🙂

**Comment by godrei** [comment]
Hi @vanwagonet and @bootstraponline please send us failed build urls, to let us identify the issue.

**Comment by bootstraponline** [comment]
https://app.bitrise.io/build/7130f25d9725686c

we are talking about it in the `#instructure` channel on Slack

**Comment by vanwagonet** [comment]
I'll try with `2.4.10` It does not let me specify the `iCloudContainerEnvironment`, but maybe it will still include it in the plist.

**Comment by vanwagonet** [comment]
I get the same error with `2.4.10` https://app.bitrise.io/build/77f8afece7ccb844

`error: exportArchive: exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was provided`

**Comment by godrei** [comment]
Hi xcode-archive 2.4.15 released, it uses the iCloudContainerEnvironment step input in case of CloudDocuments capability for the ipa export

**Comment by godrei** [comment]
I'll close this issue, but if you see an issue with the latest version please submit a new issue report!
