### ISSUE TITLE
No scheme found

### ISSUE THREAD

**Issue by poldz123** [bitrise-io/steps-xcode-archive#129]
When archiving, it is not generating the IPA files, it is always saying that the scheme could not be found within the workspace.

```Exporting ipa with ExportOptions.plist
No custom export options content provided, generating export options...
export-method specified: app-store
no scheme found with name: APP_SCHEME in workspace:APP_WORKSPACE.xcworkspace
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | xcode-archive@2.4.15 (exit code: 1)                           | 184 sec  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-xcode-archive/issues      |
| Source: https://github.com/bitrise-io/steps-xcode-archive                    |
+---+---------------------------------------------------------------+----------+
```

I have downgraded to `2.4.10` and now it works. What may caused the problem with the latest build?

**Comment by bitce** [comment]
Hi @poldz123 could you send us a build URL to be able to look at this issue?

**Comment by poldz123** [comment]
Hi @bitce, 

Here is the URL of the build: https://app.bitrise.io/build/e61b2154b49de6c3

**Comment by bitce** [comment]
Thanks! Just to clarify: is the same configuration working on step version 2.4.10? If so, can you send us  an URL about succeeding that way as well please?

**Comment by poldz123** [comment]
Yes it is the same configuration on 2.4.10 when it succeeded.

https://app.bitrise.io/build/ee0a4c55a98c9f84

**Comment by BirmacherAkos** [comment]
Hi @poldz123 !

Thanks for the report.

Could you please send us the .xcodeproj and the .xcworkspace files of your project via the on-site chat?
It would help us figure out what is the problem.
(On Bitrise.io the button on the bottom right)
![screenshot 2018-10-08 at 10 30 48](https://user-images.githubusercontent.com/37296013/46608230-591a3e80-cb04-11e8-8c5a-5d509631b33c.png)

**Comment by shpuntov** [comment]
This is reproduced for me on 2.4.16 version. Downgrading to 2.4.15, which worked just fine.

**Comment by keenen** [comment]
> This is reproduced for me on 2.4.16 version. Downgrading to 2.4.15, which worked just fine.

This worked for us as well.

**Comment by Fawxy** [comment]
This has also happened to us, the fix was downgrading as mentioned before

**Comment by BirmacherAkos** [comment]
Hi @shpuntov, @keenen, @Fawxy !

Sorry for the inconvenience.
The Tooling Team is working on a fix. 

Could you please send us the last failed build's URL, and the  .xcodeproj, .xcworkspace files of your project via the on-site chat?
It would help us figure out what is the problem.

**Comment by godrei** [comment]
Hi @poldz123 ,
we released a new step version which fixes this issue: https://github.com/bitrise-io/steps-xcode-archive/releases/tag/2.4.17

I'll close this issue, but if you need more info/help just open a new issue!

**Comment by krokyze** [comment]
Having the same issue on 2.4.21, downgrading to 2.4.20 solves it.

**Comment by BirmacherAkos** [comment]
Hi @krokyze  !

Could you please send us the .xcodeproj and the .xcworkspace files of your project via the on-site chat (with the mention of this Github issue)?
It would help us figure out what is the problem.
(On Bitrise.io the button on the bottom right)
![screenshot 2018-10-08 at 10 30 48](https://user-images.githubusercontent.com/37296013/46608230-591a3e80-cb04-11e8-8c5a-5d509631b33c.png)
