### ISSUE TITLE
Step fails with "no scheme found with name" on version 2.4.15

### ISSUE THREAD

**Issue by dgranahan** [bitrise-io/steps-xcode-archive#131]
Hello,

I'm trying to use xcode-archive 2.4.15 but I am getting a failure for "no scheme found". This looks similar to https://github.com/bitrise-io/steps-xcode-archive/issues/120 and https://github.com/bitrise-io/steps-xcode-archive/issues/121. Version 2.4.13 was reported to fix this issue but downgrading to this version did not work for me. Downgrading to 2.4.10 fixes this issue.

```
** ARCHIVE SUCCEEDED **

Archive infos:
team: <redacted>
profile: iOS Team Provisioning Profile: * (<redacted>)
export: development
xcode managed profile: true

Exporting ipa from the archive...

Exporting ipa with ExportOptions.plist
No custom export options content provided, generating export options...
export-method specified: ad-hoc
no scheme found with name: TestAppObjC in workspace: TestAppObjC/TestAppObjC.xcworkspace
```

**Comment by naptej** [comment]
Hi @dgranahan, thanks for reporting! This seems identical to #129

**Comment by bitce** [comment]
Hi @dgranahan thanks for reporting! This seems indentical to #129

**Comment by dgranahan** [comment]
@bitce yes agreed. Sorry, I didn't see that issue!
