### ISSUE TITLE
Export Failed: target not found: ED093619217F8FAE00822AB5

### ISSUE THREAD

**Issue by liuzhen2008** [bitrise-io/steps-xcode-archive#137]
How do I deal with this error here?

Below is a snippet of the log.

The archive seems to be successful, but it somehow ended up with this error here.

```
▸ Generating 'MyTarget\ Prod\ CI.app.dSYM'
▸ Running script '[CP] Copy Pods Resources'
▸ Touching MyTarget\ Prod\ CI.app (in target: MyTarget Prod CI)
▸ Archive Succeeded

[34;1mArchive infos:[0m
team: My Inc (XXXXXX)
profile: My Profile Prod (xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx)
export: app-store
xcode managed profile: false

[34;1mExporting ipa from the archive...[0m

Exporting ipa with ExportOptions.plist
No custom export options content provided, generating export options...
export-method specified: app-store
[31;1mtarget not found: ED093619217F8FAE00822AB5[0m
|                                                                              |

```

**Comment by liuzhen2008** [comment]
Looks like I missed a commit locally that updates the blueprintidentifiers in the xscheme file

**Comment by bitce** [comment]
Glad to see you've managed to sort this quickly! 🙂

**Comment by default** [comment]
I'm having the same issue with my project
Could anyone, please, explain what exactly needs to be done in order to fix this?

**Comment by liuzhen2008** [comment]
@default 

In my case it was something in the project.xcodeproj/xcshareddata/xcschemes/Prod CI.xcsheme file specifying a wrong BlueprintIdentifier = "YYYYYYYY"

I am not sure exactly how this happen, but what fixed it for me was the following:
1. Product -> Scheme -> Manage Scheme

Click around in the new window (I didn't modify anything).

And then just close the window. Observe git, magically that file is updated with a new BlueprintIdentifier which seems to work correctly with bitrise builds.

**Comment by default** [comment]
Can confirm, this, indeed, fixed the issue.
To clarify: I had to deselect and then select the deselected scheme again.
