### ISSUE TITLE
Add the ability to persist (download) the generated archive.

### ISSUE THREAD

**Issue by czaku** [bitrise-io/steps-xcode-archive#26]
It would be great to have this functionality. There is lots of issues with bitcode enabled apps and dSyms. Only having the xcarchive accessible gives you the full assurance you have the correct dSyms. Fabric doesn't retrieve them automatically for bitcode enabled apps.

**Comment by godrei** [comment]
Hi @czaku ,
we shipped a new version 1.7.0 (https://github.com/bitrise-io/steps-xcode-archive/releases/tag/1.7.0), which adds the ability to persist the generated xcarchive.
Thanks for the contribution! :)
