### ISSUE TITLE
Allow the IPA to be renamed, instead of using the Scheme name

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/steps-xcode-archive#3]
The Scheme might contain space or other non acceptable characters

The default option can be the Scheme name, but an optional IPA name option would help.

**Comment by godrei** [comment]
Hi @viktorbenei ,
new version [2.0.0](https://github.com/bitrise-io/steps-xcode-archive/releases/tag/2.0.0) is released.

From this version you can use `artifact_name` to controller the generated output file base names.
