### ISSUE TITLE
Doesn't support swift 2.2

### ISSUE THREAD

**Issue by 0xABC** [bitrise-io/steps-xcode-archive#30]

**Comment by viktorbenei** [comment]
It does, but you have to select the Xcode 7.3 stack: http://blog.bitrise.io/2016/03/22/xcode-7-3-final-is-now-available.html

If you'd have any issue after selecting the 7.3 stack let us know!

**Comment by 0xABC** [comment]
right. Sorry @viktorbenei :)

**Comment by viktorbenei** [comment]
No problem - if you'd have any issue feel free to create a new ticket!
