### ISSUE TITLE
Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found."

### ISSUE THREAD

**Issue by morugu** [bitrise-io/steps-xcode-archive#37]
I was completed be able to Xcode -> Product -> Archive and Export .ipa with no error in Mac(OS X 10.11.5).
but getting this error in Bitrise workflow.

```
Exporting IPA from generated Archive...
  $ set -o pipefail && xcodebuild -exportArchive -archivePath "/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise-xcarchive.2XeBFtsX/ProjectName.xcarchive" -exportPath "/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise-xcarchive.5gP61qY6" -exportOptionsPlist "/Users/vagrant/deploy/export_options.plist" | xcpretty

2016-06-12 20:45:30.711 xcodebuild[3717:12709] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/ProjectName_2016-06-12_20-45-30.706.xcdistributionlogs'.
2016-06-12 20:45:31.000 xcodebuild[3717:12709] [MT] DeveloperPortal: Using store at URL (file:///Users/vagrant/Library/Developer/Xcode/DeveloperPortal%207.3.1.db).
2016-06-12 20:45:40.494 xcodebuild[3717:12709] [MT] IDEDistribution: Step failed: <IDEDistributionThinningStep: 0x7f8989c2a750>: Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
error: exportArchive: No applicable devices found.

Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}

|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | xcode-archive@1.8.0 (exit code: 70)                          | 406 sec  |
+----+--------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-new-xcode-archive/issues  |
| Source: https://github.com/bitrise-io/steps-new-xcode-archive                |
+----+--------------------------------------------------------------+----------+
```

already tried the following links.

http://stackoverflow.com/questions/33041109/xcodebuild-no-applicable-devices-found-when-exporting-archive
http://stackoverflow.com/questions/33901132/export-failed-error-using-xcodebuild-command-line-tool
https://forums.developer.apple.com/message/75096#75096

**Comment by viktorbenei** [comment]
Hi,

Can you please include the content of `exportOptionsPlist`? - it should be printed right before these logs

**Comment by morugu** [comment]
added exportOptiionsPlist.
however same error occurred.

exportPlist.plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>teamID</key>
        <string>myTeamId</string>
        <key>method</key>
        <string>ad-hoc</string>
        <key>uploadSymbols</key>
        <true/>
        <key>uploadBitcode</key>
        <false/>
    </dict>
</plist>

```

error logs.
```
Exporting IPA from generated Archive...
  $ xcodebuild -exportArchive -archivePath "/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise-xcarchive.lZPITzI4/ProjectName.xcarchive" -exportPath "/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/bitrise-xcarchive.czxsuo01" -exportOptionsPlist "exportPlist.plist"

2016-06-13 21:04:55.957 xcodebuild[3669:11911] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/lb/8n5bn9k975qgw662jpqdy7mm0000gn/T/ProjectName_2016-06-13_21-04-55.957.xcdistributionlogs'.
2016-06-13 21:04:56.035 xcodebuild[3669:11911] [MT] DeveloperPortal: Using store at URL (file:///Users/vagrant/Library/Developer/Xcode/DeveloperPortal%207.3.1.db).
2016-06-13 21:05:02.980 xcodebuild[3669:11911] [MT] IDEDistribution: Step failed: <IDEDistributionThinningStep: 0x7fa6ec19ae20>: Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
error: exportArchive: No applicable devices found.

Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
```

**Comment by viktorbenei** [comment]
Can you try to re-export your Certificate (p12) and download the Provisioning Profile from the Apple Developer Portal directly, and upload these to Bitrise.io ?

This issue can be related to invalid/wrong code signing files, at least so far it mostly was related to.

**Comment by morugu** [comment]
I tried it. but same error.
other repositories has no problem. only this repository has "No applicable device found" error.
Is there something that is considered to be the cause of that?

**Comment by viktorbenei** [comment]
Could you please send us the full build log in email / through the on-site chat?

Usually this error (if you use the latest steps) is related to the code signing files and not to a configuration / code, but the build log would help a lot!

**Comment by morugu** [comment]
ok. I'll send you.

**Comment by viktorbenei** [comment]
Hi,

We just released a new version of this step which now has an option to use the deprecated export option of Xcode. After some experimenting we found that there are projects which will always fails with the "No applicable devices found." error, regardless of the code signing files, **but** it'll succeed with the old/deprecated export option of Xcode.

So, to use this option, just upgrade to the latest version (1.8.1) and set the "use_deprecated_export" option to "yes".

Please let us know if this fixes your issue too!

**Comment by morugu** [comment]
Hi,

I confirmed fixed issue with "No applicable devices found" in 1.8.1.
I am grateful for your prompt response!

**Comment by viktorbenei** [comment]
Thanks for reporting @morugu !

**Comment by madhikarma** [comment]
Hi there, I ran into this issue locally with an Xcode build script (the legacy build API works but the exportOptions approach failed with the same message)

I found it to be related to using RVM or more specifically not using system Ruby (it seems Xcode has a dependency on it). Switching to system ruby (`rvm use system`) allowed the export options plist approach to work 

Locally it's fine but in a CI environment I'm not sure what's best, the legacy API works but will mean that Bitcode can't be supported from what I understand.

Links

https://twitter.com/madhikarma/status/792457412196327425
https://t.co/TnOOXSjXDc
https://github.com/fastlane/fastlane/issues/3184
https://gist.github.com/claybridges/cea5d4afd24eda268164

**Comment by viktorbenei** [comment]
This step specifically switches back to `rvm use system` (https://github.com/bitrise-io/steps-xcode-archive/blob/master/step.sh#L451) if RVM is found, as well as tries to invalidate all other ruby version manager for the export (where the ruby version matters) - https://github.com/bitrise-io/steps-xcode-archive/blob/master/step.sh#L324

If you still get the `Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found."` error, it's more likely to be related to your Xcode project (and Xcode's buggy export handling when you don't use the legacy export method), something like: http://stackoverflow.com/questions/39634404/xcodebuild-exportarchive-no-applicable-devices-found

**Comment by viktorbenei** [comment]
If anyone would have this issue today, please __do not__ change to the legacy/deprecated mode!

Instead, make sure that you use the latest version of this __Xcode Archive__ step, as the latest versions do collect and expose the "ide distribution" logs of Xcode. So far these logs included the actual error in every case we saw.

When running on bitrise.io, make sure that you have a __Deploy to Bitrise.io__ step in your workflow, that will attach all these additional Xcode logs (including the ide distribution error logs) to the build. You will be able to see these on the build's page, in the _Apps & Artifacts_ section. Check those files, you should see the error in one of those.
