### ISSUE TITLE
Code=14 "No applicable devices found."

### ISSUE THREAD

**Issue by Reedyuk** [bitrise-io/steps-xcode-archive#39]
Im getting this error when trying to archive.

`Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}`

I have found the solution to work locally for me was:

`rvm system`

This seems to resolve the issue, i will create a quick bash step to run before i archive to see if this fixes the issue on bitrise.

**Comment by viktorbenei** [comment]
RVM is not installed on the VMs :/

Thanks for reporting the issue!

**Comment by Reedyuk** [comment]
thanks viktor, how do i fix this issue then?

**Comment by viktorbenei** [comment]
It's usually related to incorrect code signing files, re-export or regenerate the flies (and upload the new ones to Bitrise.io) , that usually solves the issue. We know only one project where that didn't fix the issue.

**Comment by Reedyuk** [comment]
ok, i will retry now.
Thanks

**Comment by viktorbenei** [comment]
Let us know how it goes!

**Comment by Reedyuk** [comment]
ah its working, it was actually related to a cocoapod library, that was causing the issue on bitrise, the other issue locally was a red herring.

**Comment by viktorbenei** [comment]
Thanks for reporting! 😉
