### ISSUE TITLE
Build started failing overnight due to missing signature

### ISSUE THREAD

**Issue by atom-r** [bitrise-io/steps-xcode-archive#63]
The error is
> Code signing is required for product type 'Application' in SDK 'iOS 10.3'

Not sure what other info to provide.

**Comment by viktorbenei** [comment]
This is an Xcode error and usually means that a dev cert/prov profile is missing.

Please follow this guide: http://devcenter.bitrise.io/ios/code-signing/#collect-the-required-files-with-codesigndoc and upload *all the files* generated by `codesigndoc` to bitrise.io. After that this error should disappear.

I'll close this ticket here, but if that wouldn't help please let us know and we'll dig deeper! ;)
