### ISSUE TITLE
Option to pass in export options plist file

### ISSUE THREAD

**Issue by jberkel** [bitrise-io/steps-xcode-archive#66]
I know I can specify an custom export options plist as a string, but it would be useful if I could pass in a filename. I have some options checked into version control and would like to use those.

**Comment by viktorbenei** [comment]
Hi @jberkel ,

It's a bit out of scope right now to add this as an input to the step, but you can do this by exporting the plist file's content as an env var and then use that in the input. Related docs: http://devcenter.bitrise.io/tips-and-tricks/expose-environment-variable/

**Comment by jberkel** [comment]
OK that works. But in general I prefer to have as much as config in my repo (and not on the CI server), that's why. Plus it's version controlled.

**Comment by viktorbenei** [comment]
Sure, but this will do exactly that.

You can commit your config into your repo, then just have a Script step which reads it and exposes it as an env var; http://devcenter.bitrise.io/tips-and-tricks/expose-environment-variable/ :

```
envman add --key MY_EXPORT_OPTIONS --valuefile ./path/to/exportOptions.plist
```

Then you can use that in this step as the export options input's value (`$MY_EXPORT_OPTIONS` in the above example).

**Comment by jberkel** [comment]
yes, that's what I did! just don't like that extra step, but it's ok.

**Comment by viktorbenei** [comment]
Ahh, OK, sorry I misunderstood you :)

**Comment by viktorbenei** [comment]
If that helps, you can keep the whole bitrise.yml config in your repo: http://devcenter.bitrise.io/tips-and-tricks/use-bitrise-yml-from-repository/
