### ISSUE TITLE
Make dSYM generation optional

### ISSUE THREAD

**Issue by jpike88** [bitrise-io/steps-xcode-archive#67]
My app is hybrid. Since updating tool version, I see this:

![screen shot 2017-07-18 at 5 52 08 pm](https://user-images.githubusercontent.com/9585787/28313672-f1b41c0c-6be1-11e7-8adf-f0751a4c4c61.png)

I have to switch on dSYM generation again as a workaround. It's a pain and slows down build/deploy cycles that some of us simply don't need

**Comment by viktorbenei** [comment]
Hi,

Thanks for reporting @jpike88 !

Indeed the preferred workaround for now is to enable dSYM generation, but if it worked in a previous version of the step without any issue you might also try to simply downgrade the step to that version (you should see the step version in the build's log).

**Comment by godrei** [comment]
Hi @jpike88 ,
thanks for the report! Currently the step expects that dsyms are generated (this is the situation in previous versions of the step as well), we will make this optional.

**Comment by godrei** [comment]
Hi @jpike88 ,
we managed to make dsym export optional in version: [2.1.0](https://github.com/bitrise-io/steps-xcode-archive/releases/tag/2.1.0)

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!
