### ISSUE TITLE
2.2.0 - failed to get provisioning profile

### ISSUE THREAD

**Issue by tomhall** [bitrise-io/steps-xcode-archive#71]
Using the recently released 2.2.0 with Xcode 9.0.x, on macOS 10.12 (Sierra), I'm getting the following build error: 

```
Exporting ipa from the archive...
Using export options
Generating export options
using export-method input: app-store
Failed to create target code sign properties mapping, error: failed to get provisioning profile - bundle id mapping, error: undefined method `end_with?' for ["airdray.xcodeproj"]:Array
```

Dropping back down to 2.1.1 works perfectly.

**Comment by godrei** [comment]
Hi @tomhall ,
thanks for the issue report!
We released a new version ([2.2.1](https://github.com/bitrise-io/steps-xcode-archive/releases/tag/2.2.1)), this version should be able to generate the exportOptions with xcode 9.

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!
