### ISSUE TITLE
Can not archive with Charts

### ISSUE THREAD

**Issue by Shinichi52** [bitrise-io/steps-xcode-archive#73]
hi,
i built success my prj with command line:
```sh
xcodebuild -workspace ios/xxx.xcworkspace -scheme xxx -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build
```
But i don't built successfully with bitrise xcode-archive. It console to message:
```sh
ios/scatter/RNScatterChartView.swift:5:8: error: no such module 'Charts'
import Charts
       ^

** ARCHIVE FAILED **


The following build commands failed:
        CompileSwift normal arm64 /xxx/ios/scatter/RNScatterChartView.swift
        CompileSwift normal arm64 /xxx/ios/bar/RNBarChartViewBase.swift
        CompileSwift normal arm64 /xxx/ios/bar/RNHorizontalBarChartManager.swift
        CompileSwift normal arm64 /xxx/ios/candlestick/RNCandleStickChartView.swift
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(5 failures)
Archive failed, error: exit status 65
```

**Comment by bloodrabbit** [comment]
Thanks for reporting @Shinichi52, we’ll check this asap!

**Comment by godrei** [comment]
Hi @Shinichi52 , 
could you please share the xcode-archive step generated build command? You can find it in the step's log after the step's config log.

**Comment by Shinichi52** [comment]
Hi @godrei.
This is logs
```sh
+------------------------------------------------------------------------------+
| (1) xcode-archive@2.0.5                                                      |
+------------------------------------------------------------------------------+
| id: xcode-archive                                                            |
| version: 2.0.5                                                               |
| collection: https://github.com/Shinichi52/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2017-09-19T09:19:13+07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[09:19:13]  * [OK] Step dependency (xcode) installed, available. 
INFO[09:19:13]  * [OK] Step dependency (go) installed, available. 

ipa export configs:
- ExportMethod: auto-detect
- UploadBitcode: yes
- CompileBitcode: yes
- TeamID: 3WCRW3Y258
- UseDeprecatedExport: no
- ForceTeamID: 3WCRW3Y258
- ForceProvisioningProfileSpecifier: 
- ForceProvisioningProfile: 
- ForceCodeSignIdentity: 
- CustomExportOptionsPlistContent:

xcodebuild configs:
- OutputTool: xcodebuild
- Workdir: /Volumes/Data/Working/xxx-au/xxx-mobile
- ProjectPath: ios/xxx.xcworkspace
- Scheme: xxx
- Configuration: 
- OutputDir: /var/folders/zh/70js388d6z12kh3b_p7lzgs80000gn/T/deploy994856376
- IsCleanBuild: yes
- XcodebuildOptions: 

step output configs:
- IsExportXcarchiveZip: yes
- ExportAllDsyms: yes
- ArtifactName: xxx

step determined configs:
- xcodebuildVersion: 8.3.3 (8E3004b)

Create the Archive ...

Forcing Development Team: 3WCRW3Y258
[09:19:13] $ xcodebuild "-workspace" "ios/xxx.xcworkspace" "-scheme" "xxx" "DEVELOPMENT_TEAM=3WCRW3Y258" "clean" "archive" "-archivePath" "/var/folders/zh/70js388d6z12kh3b_p7lzgs80000gn/T/__archive__898314081/xxx.xcarchive"

User defaults from command line:
    IDEArchivePathOverride = /var/folders/zh/70js388d6z12kh3b_p7lzgs80000gn/T/__archive__898314081/xxx.xcarchive
```

**Comment by viktorbenei** [comment]
@Shinichi52 can you please share the rest of the step's log? From the header to the footer.

A question: does this happen on your own Mac or on bitrise.io? From this:

```
- Workdir: /Volumes/Data/...
```

it seems it's not running on bitrise.io

**Comment by Shinichi52** [comment]
@viktorbenei i'm using bitrise cli and build on mac
here is my full logs
[Untitled-1.txt](https://github.com/bitrise-io/steps-xcode-archive/files/1314593/Untitled-1.txt)

**Comment by viktorbenei** [comment]
thanks @Shinichi52 , we'll look into it ASAP! :)

**Comment by Shinichi52** [comment]
I hope you will fix it soon. I'm using bitrise for automation building my application. I can not building it now :(

**Comment by viktorbenei** [comment]
@Shinichi52 from your log: `xcode-archive@2.0.5`

that's a terribly outdated version of this step. Can you please upgrade to the latest version and try it again?

**Comment by Shinichi52** [comment]
hi @viktorbenei: i tried with xcode-archive@2.3.0. it's not woking.
here my logs:
[log.txt](https://github.com/bitrise-io/steps-xcode-archive/files/1319725/log.txt)

**Comment by viktorbenei** [comment]
Thanks @Shinichi52 , we'll check it ASAP! :)

**Comment by godrei** [comment]
Hi @Shinichi52 ,
in the build command you sent: `-sdk iphonesimulator`, this means that build command builds for iPhoneSimulator.
This step is designed to generate an ipa file from your project, so it archives your project and exports and ipa file.
Are you able to archive your project and export an ipa file on your local machine?

**Comment by Shinichi52** [comment]
i tried my command after remove ```-sdk iphonesimulator```. It's not work too. I tried deloy to Appstore with xcode 8.3.3. it's working fine :( Thanks for supported. This is not a bug of bittrise

**Comment by godrei** [comment]
I'll close this issue, but if you need more info/help just let us know and we'll reopen it!

**Comment by moazkh60** [comment]
This is still a bug and same is happening while archiving charts library.

**Comment by bitce** [comment]
Hey @moazkh60 can you send us a build URL please?
