### ISSUE TITLE
Archive failed, error: exit status 65

### ISSUE THREAD

**Issue by mauker** [bitrise-io/steps-xcode-archive#76]
If you can't find the reason of the error in the log, please check the raw-xcodebuild-output.log
The log file is stored in $BITRISE_DEPLOY_DIR, and its full path
is available in the $BITRISE_XCODE_RAW_RESULT_TEXT_PATH environment variable
Archive failed, error: exit status 65
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | xcode-archive@2.2.0 (exit code: 1)                            | 41 sec   |
+---+---------------------------------------------------------------+----------+
| Update available: 2.2.0 -> 2.2.1                                             |
| Issue tracker: https://github.com/bitrise-io/steps-xcode-archive/issues      |
| Source: https://github.com/bitrise-io/steps-xcode-archive                    |
+---+---------------------------------------------------------------+----------+

**Comment by godrei** [comment]
Hi, could you please attach your `raw-xcodebuild-output.log`?

**Comment by mauker** [comment]
Thanks for you answer, because I think I found the problem:

No profiles for 'br.com.ipiranga.abasteceai.quality' were found:  Xcode couldn't find a provisioning profile matching 'br.com.ipiranga.abasteceai.quality'.

[raw-xcodebuild-output.txt](https://github.com/bitrise-io/steps-xcode-archive/files/1310632/raw-xcodebuild-output.txt)

**Comment by godrei** [comment]
Based on the log it seems you did not upload the required profiles to bitrise.

You can run [codesigndoc](https://github.com/bitrise-tools/codesigndoc) to collect the required code singing files on your machine.
