### ISSUE TITLE
[2.1.1] App requires a provisioning profile with the Push Notifications feature

### ISSUE THREAD

**Issue by patrickbussmann** [bitrise-io/steps-xcode-archive#86]
Hello,

I'm getting problems with version 2.1.1 of this step.

This is the `mobileprovision` file. (censored important details)

	<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
	<plist version="1.0">
	<dict>
		<key>AppIDName</key>
		<string>App</string>
		<key>ApplicationIdentifierPrefix</key>
		<array>
		<string>1A234BCD56</string>
		</array>
		<key>CreationDate</key>
		<date>2017-10-15T21:57:36Z</date>
		<key>Platform</key>
		<array>
			<string>iOS</string>
		</array>
		<key>DeveloperCertificates</key>
		<array>
			<data>MIIFwTCCBKmgAwSZS/P+C5zc1/jAu+OAw==</data>
		</array>
		<key>Entitlements</key>
		<dict>
			<key>keychain-access-groups</key>
			<array>
				<string>1A234BCD56.*</string>		
			</array>
			<key>get-task-allow</key>
			<false/>
			<key>application-identifier</key>
			<string>1A234BCD56.de.app</string>
			<key>com.apple.developer.associated-domains</key>
			<string>*</string>
			<key>com.apple.developer.team-identifier</key>
			<string>1A234BCD56</string>
			<key>aps-environment</key>
			<string>production</string>
			<key>beta-reports-active</key>
			<true/>
		</dict>
		<key>ExpirationDate</key>
		<date>2018-04-16T21:41:49Z</date>
		<key>Name</key>
		<string>App</string>
		<key>TeamIdentifier</key>
		<array>
			<string>9T424JFK46</string>
		</array>
		<key>TeamName</key>
		<string>Company</string>
		<key>TimeToLive</key>
		<integer>182</integer>
		<key>UUID</key>
		<string>31d60604-6d1b-44e9-b6ce-a0ba0f752ba2</string>
		<key>Version</key>
		<integer>1</integer>
	</dict>
	</plist>

The important thing is:

    <key>aps-environment</key>
    <string>production</string>

So I think push notification feature is set.

The error message is:

    error: exportArchive: "APP.app" requires a provisioning profile with the Push Notifications feature.

The log says:

	** ARCHIVE SUCCEEDED **

	Exporting ipa from the archive...

	Using export options
	Generating export options
	auto-detect export method, based on embedded profile
	detected export method: app-store
	generated export options content:

	<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
	<plist version="1.0">
		<dict>
			<key>method</key>
			<string>app-store</string>
		</dict>
	</plist> <nil>

The project is an Ionic / Cordova one. But I think this doesn't matter. Or?

Thanks in Advance!

P.S. Normally I will investigate the problem by myself. But maybe someone have more informations about this. Maybe this is a wellknown problem. Maybe I must generate new certificate with provisioning profile.

I will test it tomorrow on my Macbook with Bitrise CLI. 👍 

Thanks in Advance!

**Comment by godrei** [comment]
Hi @patrickbussmann , 
thanks for the report! Could you please contact us on bitrise-on site chat? I would need to take a look on your full build.log file.

**Comment by patrickbussmann** [comment]
Yes I can do in few Minutes. (Up to half Hour)

With XCode 8.3 I get no Problems. But with 9 there is something new 😔

**Comment by patrickbussmann** [comment]
Another error if I'm not using `Manual` provisioning.

```
Code Signing Error: APP has conflicting provisioning settings. APP is automatically signed, but provisioning profile 31d60604-6d1b-44e9-b6ce-a0ba0f752ba2 has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor, or switch to manual signing in the project editor.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.0'
```

**Comment by viktorbenei** [comment]
Hi @patrickbussmann ! 👋  :)

That seems to be an unrelated error - can you please create a new issue report for it? :)

**Comment by patrickbussmann** [comment]
Hi @viktorbenei,

I think the latest error with provisioning settings are because I commented out a line which changes the Automated Signing to Manual one.
So should I create a ticket for that or not? I think its not relevant because else the plugin must modify this setting manually.

**Comment by viktorbenei** [comment]
I'd say that's up to you @patrickbussmann ;) But if you'd like to create that please do that in a separate issue, for easier tracking :)

**Comment by godrei** [comment]
@patrickbussmann could you please try the [new version of the step](https://github.com/bitrise-io/steps-xcode-archive/releases/tag/2.3.6)?

**Comment by godrei** [comment]
I'll close this issue, but if you need more info/help just let us know and we'll reopen it!
