### ISSUE TITLE
[2.3.5] Umlauts in company = error: exportArchive: No certificate for team '1A234BCD56' matching 'iPhone Distribution: A&B CD EF (haftungsbeschr\xC3\xA4nkt)' found

### ISSUE THREAD

**Issue by patrickbussmann** [bitrise-io/steps-xcode-archive#87]
Before I'm going back to 2.1.1 I got this problem here with newest 2.3.5. In 2.1.1 everything works fine.
Certificate step here version 1.9.1. (on the working one it was 1.8.8) #86

**Log:**

	Installed profiles:
	BitriseBot-Wildcard (548cd560-c511-4540-8b6b-cbec4a22f49d)
	exportType: development
	teamID: 72SA8V3WYL
	bundleID: *
	expirationDate: 2018-02-17 09:33:57 +0000 UTC
	certificates:
	- iPhone Developer: Bitrise Bot (VV2J4SV8V4)
	  serial: 5DA2A94D5F7D931E
	  teamID: 72SA8V3WYL
	App
	exportType: app-store
	teamID: 1A234BCD56
	bundleID: de.app
	expirationDate: 2018-04-16 21:41:49 +0000 UTC
	certificates:
	- iPhone Distribution: A&B CD EF (haftungsbeschr\xC3\xA4nkt) (1A234BCD56)
	  serial: 12A3BCDE4FGH56IJ
	  teamID: 1A234BCD56
	Resolving CodeSignGroups:
	Creating certificate profiles mapping
	certificate: iPhone Developer: Bitrise Bot (VV2J4SV8V4) [5DA2A94D5F7D931E] is installed
	certificate: iPhone Distribution: A&B CD EF (haftungsbeschr\xC3\xA4nkt) (1A234BCD56) [12A3BCDE4FGH56IJ] is installed

	[...]

	checking certificate (12A3BCDE4FGH56IJ) group:
	profile (App) MATCHES for bundle id (de.app) and export method (app-store)
	matching profiles: 1 should be: 1

	Resolved CodeSignGroups:
	codeSignIdentity: subject= /UID=1A234BCD56/CN=iPhone Distribution: A&B CD EF (haftungsbeschr\xC3\xA4nkt) (1A234BCD56)/OU=1A234BCD56/O=A&B CD EF (haftungsbeschr\xC3\xA4nkt)/C=US
	bundle ID: de.app is provisioned by: App

	App was signed with NON xcode managed profile when archiving,
	only NOT xcode managed profiles are allowed to sign when exporting the archive.
	Removing xcode managed CodeSignInfo groups

	generated export options content:
	<?xml version="1.0" encoding="UTF-8"?>
	<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
	<plist version="1.0">
		<dict>
			<key>method</key>
			<string>app-store</string>
			<key>provisioningProfiles</key>
			<dict>
				<key>de.app</key>
				<string>31d60604-6d1b-44e9-b6ce-a0ba0f752ba2</string>
			</dict>
			<key>signingCertificate</key>
			<string>iPhone Distribution: A&B CD EF (haftungsbeschr\xC3\xA4nkt) (1A234BCD56)</string>
			<key>teamID</key>
			<string>1A234BCD56</string>
		</dict>
	</plist> <nil>

	error: exportArchive: No certificate for team '1A234BCD56' matching 'iPhone Distribution: A&B CD EF (haftungsbeschr\xC3\xA4nkt) (1A234BCD56)' found

I think it's because of this `\xC3\xA4`. Because in 2.1.1 it was working great - except missing push notifications feature 😢 

Here I will not spend more time because I'm stay on 2.1.1 in the meanwhile.
Its bad that I haven't the time to check this issue and fix it. I would like to help. But the App needs to be built 😔

**Comment by viktorbenei** [comment]
Hi @patrickbussmann ,

Thanks for the issue report, and for all the details! Glad to hear 2.1.1 works for you, sorry for the inconvenience, we'll try to fix this ASAP and let you know as soon as the fix is available so you can upgrade! :)

**Comment by godrei** [comment]
Hi @patrickbussmann ,
we released a new version ([2.3.6](https://github.com/bitrise-io/steps-xcode-archive/releases/tag/2.3.6)) of the step, this version fixes this issue.
Thanks for the report.
I'll close this issue, but if you need more info/help just let us know and we'll reopen it!

**Comment by patrickbussmann** [comment]
Really great jobs guys! @godrei @viktorbenei 

After that work's I wanted to test your Ionic Archive step and find out that this is really really brilliant!
App builds successfully without issues and is deliverable directly. 😍

If I'm thinking back to the moment when I had time and started this ionic story 👍 
https://github.com/bitrise-community/steps-ionic

Many thanks. Really happy to see the rapid development of Bitrise. 🎈  Great job! 👍 🎉

**Comment by viktorbenei** [comment]
Thats awesome to hear @patrickbussmann and **thanks for everything**, including the ionic step (helped a lot!) and this PR! You rock! ;)
