### ISSUE TITLE
[2.3.5] Codesign grouping bug

### ISSUE THREAD

**Issue by simonmitchell** [bitrise-io/steps-xcode-archive#89]
It looks like there is a bug with the CodeSign grouping code recently introduced to fix exporting an archive in Xcode 9.

We're trying to sign an app using the `app-store` method with both a main target and a push notification extension. It seems like there's a bug in picking out the correct code signing group, but I'm not entirely sure what it's being caused by:

# Log:

```
certificate: 446FE307C20B96B8 included in profiles:

- O2 Touch Notification App Store
- iOS Team Store Provisioning Profile: com.englandrugby.o2touch
- iOS Team Store Provisioning Profile: com.englandrugby.o2touch.EventNotification
- O2 Touch App Store

certificate: 1B184E542FC908A3 included in profiles:

- iOS Team Store Provisioning Profile: com.rugbyfootballunion.o2touch
- O2 Touch App Store
- O2 Touch Notification App Store
- iOS Team Store Provisioning Profile: com.rugbyfootballunion.o2touch.EventNotification

certificate: 249F9F17BCC3055E included in profiles:

- iOS Team Provisioning Profile: com.rugbyfootballunion.o2touch
- iOS Team Provisioning Profile: com.rugbyfootballunion.o2touch.EventNotification

certificate: 5DA2A94D5F7D931E included in profiles:

- BitriseBot-Wildcard

Creating CodeSignGroups

checking certificate (446FE307C20B96B8) group:
profile (O2 Touch Notification App Store) does not provision bundle id: com.englandrugby.o2touch.EventNotification
profile (iOS Team Store Provisioning Profile: com.englandrugby.o2touch.EventNotification) does not provision bundle id: com.englandrugby.o2touch.EventNotification
profile (iOS Team Store Provisioning Profile: com.englandrugby.o2touch) MATCHES for bundle id (com.englandrugby.o2touch) and export method (app-store)
profile (O2 Touch Notification App Store) MATCHES for bundle id (com.englandrugby.o2touch.EventNotification) and export method (app-store)
matching profiles: 2 should be: 2
```

The correct certificate to be used here should be the `446FE307C20B96B8` group. As you can see at the top, this is included in the `O2 Touch Notification App Store` profile (com.englandrugby.o2touch.EventNotification), and the `O2 Touch App Store` profile (com.englandrugby.o2touch). However when the Creating CodeSignGroups part of the process happens it seems to only have the `O2 Touch Notification App Store` profile, and so it falls back to the Xcode generated provisioning profile, which then fails because of:

```
Export TeamID specified: 25H7BM6YWK, filtering CodeSignInfo groups...
Both xcode managed and NON xcode managed profiles in code singing group
```

And then:

```
error: exportArchive: Provisioning profile "iOS Team Store Provisioning Profile: com.englandrugby.o2touch" is Xcode managed, but signing settings require a manually managed profile.
Error Domain=IDEProfileQualificationErrorDomain Code=12 "Provisioning profile "iOS Team Store Provisioning Profile: com.englandrugby.o2touch" is Xcode managed, but signing settings require a manually managed profile." UserInfo={IDEProfileQualificationError_Profile=<DTDKProvisioningProfile 0x7fc374b0b700: UUID: 9fd2e6fd-ad39-4ebb-9407-0f5d23a965a8, name: iOS Team Store Provisioning Profile: com.englandrugby.o2touch, team: 25H7BM6YWK (3 SIDED CUBE DESIGN LTD), platform: iOS>, NSLocalizedDescription=Provisioning profile "iOS Team Store Provisioning Profile: com.englandrugby.o2touch" is Xcode managed, but signing settings require a manually managed profile.}
** EXPORT FAILED **
```

**Comment by viktorbenei** [comment]
Hi @simonmitchell ,

Thanks for the bug report! :)

Just to be sure: did you try it with the previous version, or can you try it? Did that work?

**Comment by simonmitchell** [comment]
@viktorbenei I think the issue here is simply the break when it matches the first provisioning profile which matches both bundle identifier and export type. I don't think this works if you have Xcode managed and NON Xcode managed profiles uploaded. 

The problem then becomes the fact that for our build configuration the provisioning profile export tool simply doesn't work in generating the correct provisioning profiles with the latest versions of the steps. I can give it a go with previous versions, for now though I'm going to try removing the Xcode team provisioning profiles and see if that fixes the issue!

**Comment by simonmitchell** [comment]
@viktorbenei okay it turns out I was correct. I removed all the App Store Team provisioning profiles and now it works! Not sure if there's any way to get the provisioning export script working now at generating the correct provisioning profiles now that Xcode 9 seems to require manually generated ones for upload to App Store! 

It could also obviously be the case that we're doing everything wrong here... but this is essentially how we've been building all of our apps for the last year and a half or so!

**Comment by godrei** [comment]
Hi @simonmitchell , 
thanks for the report! Could you please contact us on bitrise.io on-site chat and send us your failed build log url?

**Comment by godrei** [comment]
I'll close this issue, but if you need more info/help just let us know and we'll reopen it!
